language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  - PACKAGE="jackline" OCAML_VERSION=4.02 EXTRA_REMOTES="https://github.com/hannesm/xmpp-opam.git"
  - PACKAGE="jackline" OCAML_VERSION=4.03 EXTRA_REMOTES="https://github.com/hannesm/xmpp-opam.git"
notifications:
  email: false
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: PACKAGE="jackline" OCAML_VERSION=4.03 EXTRA_REMOTES="https://github.com/hannesm/xmpp-opam.git"
